window.traductions = {
    french: {
        home: "Menu d'accueil",
        settings: "PARAMETRES",
        guide: "GUIDE",
        register: "INSCRIPTION",
        login: "CONNEXION",
        play: "JOUER",
        welcome_unconnected: "Hey jeune hacker, venez commencer une nouvelle partie ou connectez vous pour continuer votre aventure.",
        welcome_connected: "Bienvenue ! Vous etes connecte",
        copyright: "Copyright...<br>Made by N.SILLAIRE, A.VIVIEN, O.LAADRAOUI",
        login_title: "Connectez-vous",
        email_label: "Adresse Email",
        email_placeholder_login: "Entrez votre adresse email ici",
        password_label: "Mot de passe",
        password_placeholder_login: "Entrez votre mot de passe ici",
        login_button: "Se connecter",
        login_missing_fields: "Veuillez remplir tous les champs",
        register_title: "Inscrivez-vous",
        email_placeholder_register: "Entrez votre adresse mail ici",
        username_label: "Pseudo",
        username_placeholder: "Entrez votre pseudo ici",
        confirm_password_label: "Confirmer le mot de passe",
        confirm_password_placeholder: "Confirmer votre mot de passe ici",
        register_button: "S'enregistrer",
        register_missing_fields: "Veuillez remplir tous les champs",
        password_mismatch: "Les mots de passe ne correspondent pas",
        factory_reset: "🔄 Réinitialiser aux valeurs par défaut",
        guide_back: "Menu d'accueil",
        guide_title: "GUIDE DU JEU NEUROPULSE",
        guide_welcome: "Bienvenue dans Neuropulse",
        guide_intro: "Plongez dans un univers cyberpunk ou l'intelligence artificielle regne en maitre. Neuropulse est un jeu d'aventure ou vous incarnez un hacker cherchant a percer les secrets d'une megacorporation.",
        guide_base_controls: "Controles de base",
        guide_movement: "Deplacement",
        guide_move_up: "Haut",
        guide_move_down: "Bas",
        guide_move_left: "Gauche",
        guide_move_right: "Droite",
        guide_pause: "Menu pause",
        guide_actions: "Actions",
        guide_interact: "Interagir",
        guide_attack: "Attaquer",
        guide_objectives: "Objectifs du jeu",
        guide_objective_infiltration: "Infiltration",
        guide_objective_infiltration_desc: "Penetrez dans les systemes securises sans vous faire detecter",
        guide_objective_combat: "Combat",
        guide_objective_combat_desc: "Affrontez les agents de securite et les IA hostiles",
        guide_objective_exploration: "Exploration",
        guide_objective_exploration_desc: "Decouvrez les secrets caches de la corporation",
        guide_tips: "Conseils pour debuter",
        guide_important: "Important :",
        guide_tip_save: "Sauvegardez regulierement votre progression",
        guide_tip_explore: "Explorez chaque zone pour trouver des objets caches",
        guide_tip_observe: "Observez les patterns des ennemis avant d'attaquer",
        guide_tip_escape: "N'hesitez pas a fuir si vous etes en difficulte",
        guide_tip_talk: "Parlez aux PNJ pour obtenir des informations cruciales",
        guide_ui: "Interface utilisateur",
        guide_hp: "Barre de sante :",
        guide_hp_desc: "Affichee en haut a gauche, surveillez-la constamment",
        guide_energy: "Energie neuronale :",
        guide_energy_desc: "Necessaire pour utiliser des competences speciales",
        guide_minimap: "Mini-carte :",
        guide_minimap_desc: "Situee en haut a droite, elle vous aide a naviguer",
        guide_inventory: "Inventaire :",
        guide_inventory_desc: "Appuyez sur",
        guide_inventory_suffix: "pour y acceder",
        guide_quote: "Dans Neuropulse, l'information est votre meilleure arme",
        save_title: "CHOIX DE LA SAUVEGARDE",
        save_subtitle: "Selectionnez un slot pour commencer votre aventure",
        save_slot: "SLOT",
        save_available: "DISPONIBLE",
        save_empty: "Emplacement vide",
        save_create: "Creer un nouveau personnage",
        save_edit: "Modifier le personnage",
        save_play: "JOUER",
        development_mode: "Mode developpement",
        development_access: "Acces rapide au jeu sans sauvegarde",
        development_launch: "LANCER LE JEU (TEMPORAIRE)",
        create_back: "Retour aux sauvegardes",
        create_title: "CREER UN PERSONNAGE",
        create_subtitle: "Configurez votre identite dans le reseau",
        first_name_label: "Prenom du personnage",
        first_name_placeholder: "Ex: Neo, Trinity, Cipher...",
        first_name_hint: "Votre nom de code dans le reseau",
        last_name_label: "Nom du personnage",
        last_name_placeholder: "Ex: Anderson, Smith, Morpheus...",
        last_name_hint: "Votre identite officielle",
        sex_label: "Sexe du personnage",
        sex_default: "-- Selectionnez une option --",
        sex_male: "Masculin",
        sex_female: "Feminin",
        sex_other: "Autre",
        create_button: "Creer le personnage",
        cancel_button: "Annuler",
        edit_title: "MODIFIER LE PERSONNAGE",
        edit_subtitle: "Mettez a jour votre identite numerique",
        current_character: "Personnage actuel",
        level: "Niveau 5",
        class_label: "Classe: Hacker",
        change_avatar: "Changer d'avatar",
        current_stats: "Statistiques actuelles",
        intelligence: "Intelligence",
        strength: "Force",
        agility: "Agilite",
        edit_warning: "Attention : La modification du personnage ne modifie que les informations cosmetiques. Vos statistiques et progression de jeu restent inchangees.",
        save_changes: "Sauvegarder les modifications",
        delete_character: "Supprimer ce personnage",
        delete_confirm: "Attention ! Etes-vous sur de vouloir supprimer ce personnage ? Cette action est irreversible !",
        delete_success: "Personnage supprime avec succes.",
        settings_title: "PARAMETRES",
        settings_subtitle: "Personnalisez votre experience de jeu",
        audio_section: "Audio",
        main_volume: "Volume principal",
        music_volume: "Volume musique",
        sfx_volume: "Volume effets sonores",
        language_region: "Langue et region",
        game_language: "Langue du jeu",
        language_french: "Francais",
        language_english: "English",
        controls: "Controles",
        controls_tip: "Cliquez sur un champ et appuyez sur la touche souhaitee pour la redefinir",
        move_up: "Deplacer vers le haut",
        move_down: "Deplacer vers le bas",
        move_left: "Deplacer vers la gauche",
        move_right: "Deplacer vers la droite",
        attack: "Attaquer",
        interact: "Interagir",
        inventory: "Inventaire",
        map: "Carte",
        reset_defaults: "Reinitialiser aux valeurs par defaut",
        save_settings: "Sauvegarder les parametres",
        reset_all: "Reinitialiser tout"
    },
    english: {
        home: "Home",
        settings: "SETTINGS",
        guide: "GUIDE",
        register: "SIGN UP",
        login: "LOGIN",
        play: "PLAY",
        welcome_unconnected: "Hey young hacker, start a new game or log in to continue your adventure.",
        welcome_connected: "Welcome! You are logged in",
        copyright: "Copyright...<br>Made by N.SILLAIRE, A.VIVIEN, O.LAADRAOUI",
        login_title: "Sign in",
        email_label: "Email address",
        email_placeholder_login: "Enter your email address here",
        password_label: "Password",
        password_placeholder_login: "Enter your password here",
        login_button: "Sign in",
        login_missing_fields: "Please fill in all fields",
        register_title: "Sign up",
        email_placeholder_register: "Enter your email address here",
        username_label: "Username",
        username_placeholder: "Enter your username here",
        confirm_password_label: "Confirm password",
        confirm_password_placeholder: "Confirm your password here",
        register_button: "Register",
        register_missing_fields: "Please fill in all fields",
        password_mismatch: "Passwords do not match",
        factory_reset:"🔄 Reset to default settings",
        guide_back: "Home",
        guide_title: "NEUROPULSE GAME GUIDE",
        guide_welcome: "Welcome to Neuropulse",
        guide_intro: "Dive into a cyberpunk world where artificial intelligence rules. Neuropulse is an adventure game in which you play as a hacker trying to uncover the secrets of a megacorporation.",
        guide_base_controls: "Basic controls",
        guide_movement: "Movement",
        guide_move_up: "Up",
        guide_move_down: "Down",
        guide_move_left: "Left",
        guide_move_right: "Right",
        guide_pause: "Pause menu",
        guide_actions: "Actions",
        guide_interact: "Interact",
        guide_attack: "Attack",
        guide_objectives: "Game objectives",
        guide_objective_infiltration: "Infiltration",
        guide_objective_infiltration_desc: "Break into secured systems without being detected",
        guide_objective_combat: "Combat",
        guide_objective_combat_desc: "Fight security agents and hostile AIs",
        guide_objective_exploration: "Exploration",
        guide_objective_exploration_desc: "Discover the corporation's hidden secrets",
        guide_tips: "Tips to get started",
        guide_important: "Important:",
        guide_tip_save: "Save your progress regularly",
        guide_tip_explore: "Explore every area to find hidden items",
        guide_tip_observe: "Watch enemy patterns before attacking",
        guide_tip_escape: "Do not hesitate to flee if you are in trouble",
        guide_tip_talk: "Talk to NPCs to get crucial information",
        guide_ui: "User interface",
        guide_hp: "Health bar:",
        guide_hp_desc: "Shown in the top left, keep an eye on it",
        guide_energy: "Neural energy:",
        guide_energy_desc: "Required to use special abilities",
        guide_minimap: "Mini-map:",
        guide_minimap_desc: "Located in the top right, it helps you navigate",
        guide_inventory: "Inventory:",
        guide_inventory_desc: "Press",
        guide_inventory_suffix: "to access it",
        guide_quote: "In Neuropulse, information is your best weapon",
        save_title: "SAVE SLOT SELECTION",
        save_subtitle: "Select a slot to start your adventure",
        save_slot: "SLOT",
        save_available: "AVAILABLE",
        save_empty: "Empty slot",
        save_create: "Create a new character",
        save_edit: "Edit character",
        save_play: "PLAY",
        development_mode: "Development mode",
        development_access: "Quick access to the game without a save",
        development_launch: "LAUNCH GAME (TEMPORARY)",
        create_back: "Back to saves",
        create_title: "CREATE A CHARACTER",
        create_subtitle: "Set up your identity in the network",
        first_name_label: "Character first name",
        first_name_placeholder: "Ex: Neo, Trinity, Cipher...",
        first_name_hint: "Your code name in the network",
        last_name_label: "Character last name",
        last_name_placeholder: "Ex: Anderson, Smith, Morpheus...",
        last_name_hint: "Your official identity",
        sex_label: "Character gender",
        sex_default: "-- Select an option --",
        sex_male: "Male",
        sex_female: "Female",
        sex_other: "Other",
        create_button: "Create character",
        cancel_button: "Cancel",
        edit_title: "EDIT CHARACTER",
        edit_subtitle: "Update your digital identity",
        current_character: "Current character",
        level: "Level 5",
        class_label: "Class: Hacker",
        change_avatar: "Change avatar",
        current_stats: "Current stats",
        intelligence: "Intelligence",
        strength: "Strength",
        agility: "Agility",
        edit_warning: "Warning: Editing the character only changes cosmetic information. Your stats and game progress remain unchanged.",
        save_changes: "Save changes",
        delete_character: "Delete this character",
        delete_confirm: "Warning! Are you sure you want to delete this character? This action cannot be undone!",
        delete_success: "Character deleted successfully.",
        settings_title: "SETTINGS",
        settings_subtitle: "Customize your game experience",
        audio_section: "Audio",
        main_volume: "Master volume",
        music_volume: "Music volume",
        sfx_volume: "Sound effects volume",
        language_region: "Language and region",
        game_language: "Game language",
        language_french: "French",
        language_english: "English",
        controls: "Controls",
        controls_tip: "Click a field and press the desired key to remap it",
        move_up: "Move up",
        move_down: "Move down",
        move_left: "Move left",
        move_right: "Move right",
        attack: "Attack",
        interact: "Interact",
        inventory: "Inventory",
        map: "Map",
        reset_defaults: "Reset to default values",
        save_settings: "Save settings",
        reset_all: "Reset all"
    }
};
